### Obtener info
GET http://localhost:3001/info

###

### Obtener una sola persona (GET)
GET http://localhost:3001/api/persons/1

###

### Borrar una nota (DELETE) - ¡Lo que querías probar!
DELETE http://localhost:3001/api/persons/1

###

### Crear una nota nueva (POST) - Para probar después
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Matías",
  "number": "040-123456"
}